<div class="pscat fgc">
	<div class="row fbc pscat">
		<div class="small-18 medium-17 medium-centered columns terminos-condiciones">
			<h1 class="azul text-center divisor">Términos y Condiciones</h1>
			
			<h3 class="subseccion-titulo">Consideraciones Generales</h3>
			<p class="text-left medium-text-justify">En el marco de esta oferta online, su socio contractual es la persona física con actividad empresarial Deysi Gabriela de Jesús Cruz Hernandez, con domicilio en el predio marcado con el numero ochocientos quince de la calle ciento treinta y tres letra A del Fraccionamiento Villa Magna del Sur quien representa la página web denominada Printome.mx</p>
			<p class="text-left medium-text-justify">Todas las entregas de printome.mx al cliente se producirán en base a las siguientes Condiciones Generales de Contrato y de Entrega. En éstas se basarán todas las ofertas y los acuerdos entre printome.mx  y el cliente y éstas se considerarán aceptadas durante todo el tiempo que persista la relación comercial. Condiciones del comprador contrarias o diferentes a éstas sólo serán vinculantes en el caso de que Printome.mx  las haya aceptado por escrito.</p>
			
			<h3 class="subseccion-titulo">Responsabilidad de la Oferta Online</h3>
			<p class="text-left medium-text-justify">Por medio de la página web printome.mx  se ponen a disposición dos tipos de tiendas. Por un lado, tiendas que han sido creadas y gestionadas por printome.mx (“tiendas printome”), por otro, tiendas que han sido creadas y gestionadas por socios de tienda independientes (“tiendas de socios“). La Información sobre el  socio de una tienda se encuentra disponible a través del enlace que se encuentra en la correspondiente tienda.</p>
			<p class="text-left medium-text-justify">La página web printome.mx es responsable únicamente por las “tienda printome ” en cuanto a todos los artículos y motivos ofrecidos en venta en las misma en el entendido que dicha tienda es de su propiedad.</p>
			<p class="text-left medium-text-justify">Cada socio es responsable de los artículos y motivos ofrecidos en una “tienda de socios“ y de la configuración de la tienda en su conjunto, previamente aprobada por la página web printome.mx</p>
			<p class="text-left medium-text-justify">En el caso de las “tiendas de socio” el explotador de la tienda o socio comercial es el único responsable de los artículos y motivos que se ofrecen en su “tienda de socio“, así como de la decoración de la tienda y de la publicidad de los artículos ofrecidos.</p>
			<p class="text-left medium-text-justify">printome.mx rechaza explícitamente los contenidos propios del explotador de la tienda o socio comercial si éstos no se ajustan a las regulaciones contempladas en estas Condiciones Generales y/o a las regulaciones de las Condiciones Generales del presente Contrato. Esto se aplica, en especial, a las violaciones del explotador de la tienda o socio comercial de la obligación de utilizar exclusivamente las Condiciones Generales de Venta que printome.mx establece para sus clientes mediante el presente contrato.</p>
			
			<h3 class="subseccion-titulo">Tiendas de Socios</h3>
			<p class="text-left medium-text-justify">Las tiendas de socios son para efectos del presente contrato, apartados establecidos en la página printome.mx que se refieren a los trabajos elaborados por diseñadores gráficos o cualesquiera personas en las cuales los mismos ofrecen en venta sus diseños a través de la página web printome.mx</p>
			<p class="text-left medium-text-justify">La responsabilidad de la tienda de socios será exclusiva del socio de negocios sin que la página web printome.mx tenga responsabilidad alguna sobre los diseños que suben las personas que registran sus productos para venta en estas “tiendas de socios”.</p>
			<p class="text-left medium-text-justify">Las tiendas de socios serán una forma de nombrar a cada diseñador o persona que suba diseños para venta al público, el cual tendrá un pseudónimo o nombre comercial con el cual se podrá identificar sus productos.</p>
			<p class="text-left medium-text-justify">Los socios de la pagina web printome.mx tendrán un procedimiento de común acuerdo con la misma a fin de subir a la página de referencia sus diseños y promoverlos en venta, asimismo podrán lanzar campañas publicitarias para la comercialización de dichos productos limitando siempre la venta de los productos la cual tiene que realizarse necesariamente a través de la página web printome.mx</p>
			<p class="text-left medium-text-justify">Una vez concretada la relación comercial entre el socio y la página web printome.mx el socio tendrá una clave de acceso a su tienda de socios pudiendo a partir de dicho momento subir sus diseños previa autorización de la página web printome.mx esto a fin de realizar la investigación acerca de derechos de propiedad sobre los diseños. Los socios que deciden entablar una relación comercial con la página web printome.mx  aceptan por este medio toda la responsabilidad que pudiera generarse derivada de la comercialización de sus diseños, incluyendo la responsabilidad de propiedad intelectual e industrial y los derechos de autor, por lo que liberan a la página web printome.mx y a sus representantes de cualquier responsabilidad legal en este sentido.</p>
			<p class="text-left medium-text-justify">Una vez han sido aprobados los diseños del socio el mismo podrá subirlos a la plataforma y ofertarlos en venta el precio de los mismos será tasado de común acuerdo entre el socio y la página web printome.mx tomando como referencia la lista de precios por servicio con que la página web printome.mx cuenta online o en la sección de la página donde se establece el costo de las prendas y las respectivas utilidades para el socio.</p>
			<p class="text-left medium-text-justify">Derivado de cada venta del producto ofertado el socio tendrá una participación en la utilidad de la misma, la cual será tasado de común acuerdo entre el socio y la página web printome.mx tomando como referencia la lista de precios por servicio con que la página web printome.mx cuenta online en la sección de la página donde se establece el costo de las prendas y las respectivas utilidades para el socio. Dicha cantidad será pagada por la página web printome.mx al socio comercial mediante los medios establecidos en la página web los cuales son en primer lugar en especie mediante el envío de un número determinado de prendas impresas con los diseños de la o las campañas que el socio haya realizado, en segundo lugar a elección del socio mediante un deposito realizado en cuenta fiscal del socio, este método de pago UNICAMENTE aplica para el caso que el Socio Comercial emita factura electrónica aprobada por el Sistema de Administración Tributaria para todos los efectos legales que procedan. En tercer lugar, con depósito en efectivo en una cuenta a nombre del Socio Comercial, siendo este último único responsable del trámite de pago de sus impuestos o cualquier otra acción necesaria referente a las políticas aplicadas por el Sistema de Administración Tributaria, deslindando de toda responsabilidad a la página web printome.mx</p>
			<p class="text-left medium-text-justify">La determinación del monto y/o porcentaje de participación en la utilidad de la venta del producto de cada socio se realizara tomando en consideración todos los factores que sean relevantes con respecto de la campaña que lance el socio comercial incluyendo el numero de diseños, el numero de productos ofertados, el diseño de la campaña, el plazo de la campaña, costo por prenda derivado del alcance de la campaña, precio público sugerido por el Socio Comercial, aclarando que la determinación de la utilidad es descontando el Impuesto al Valor Agregado del precio público establecido.</p>
			<p class="text-left medium-text-justify">Los diseños que cada socio sube a la página web printome.mx para su comercialización son propiedad de cada socio; pero al subir el mismo a la página web mediante la tienda de socios otorga el derecho a printome.mx para a su vez realizar promoción y campañas del mismo, imprimir, comercializar y vender el mismo, con la participación en la utilidad que fuere aplicable de acuerdo al listado de precios que se encuentran en la página web, este derecho otorgado a printome.mx y a sus representantes no puede ser reclamado por cualquier vía ya que la relación comercial implica derechos y obligaciones entre las partes y únicamente puede el socio comercial reclamar el pago de la participación en la utilidad de acuerdo al listado de precios mencionado con anterioridad y/o a los cálculos que arroje el sistema en línea donde se determina el costo del producto según los parámetros de la campaña establecidos por el Socio Comercial, siempre que dichos parámetros se cumplan a cabalidad, restando el Impuesto al Valor Agregado del producto a la hora de determinar la utilidad, dicho pago deberá ser realizado en la forma en que se establece en el presente contrato.</p>
			
			<h3 class="subseccion-titulo">Envío / Entrega</h3>
			<p class="text-left medium-text-justify">El suministro del producto solicitado se realiza fundamentalmente durante las tres semanas siguientes a que el cliente haya recibido la confirmación de pedido o que haya concluido la campaña de venta del socios que es cuando se determina la viabilidad de la misma e inicia el proceso productivo de las prendas vendidas. Las fechas y plazos de entrega únicamente son obligatorias  en cuanto que printome.mx las aceptó explícitamente y por escrito.</p>
			<p class="text-left medium-text-justify">La entrega de los pedidos se realiza dentro la Republica Mexicana y en los Países que se estipulen en la página de la empresa printome.mx</p>
			<p class="text-left medium-text-justify">La entrega de los pedidos se realizara por medio de un servicio de mensajería a escoger por printome.mx, El cliente asumirá un importe total del envío el cual podrá variar según el valor del pedido y el lugar de envío. Los actuales precios de envío pueden verse en www.printome.mx en el cotizador de la página.</p>
			<p class="text-left medium-text-justify">Si por causas ajenas a la empresa no fuese posible realizar la entrega del producto dentro del plazo de tres semanas mencionado en el presente contrato a partir de la fecha de envío del correo electrónico de confirmación de pedido o tres semanas después de la terminación de la campaña del socio, printome.mx en ese caso informará al cliente mediante correo electrónico a más tardar al vencimiento del plazo. El cliente podrá en ese caso solicitar el reembolso de la cantidad pagada u optar por una vía de entrega más rápida.</p>
			
			<h3 class="subseccion-titulo">Reserva de la Propiedad</h3>
			<p class="text-left medium-text-justify">La mercancía será propiedad de printome.mx hasta la entrega de la misma. En el caso de que el cliente sea un comercio o un comerciante, printome.mx se reserva la propiedad de toda la mercancía hasta que reciba el pago total de la misma.</p>

			<h3 class="subseccion-titulo">Garantía</h3>
			<p class="text-left medium-text-justify">Los datos, dibujos, ilustraciones, datos técnicos, descripciones de peso, medidas y prestaciones que aparezcan en prospectos, catálogos, circulares, anuncios o listas de precios, sólo tienen carácter  informativo, printome.mx  no asume responsabilidad alguna con respecto a que esos datos sean correctos. En lo que se refiere al tipo y al volumen del envío sólo tendrán validez los datos que aparecen en la confirmación del pedido.</p>
			<p class="text-left medium-text-justify">En el caso de que exista algún defecto de fábrica que deba cubrir la garantía, el cliente tendrá derecho en el marco de las disposiciones legales a exigir cumplimiento posterior dentro de los treinta días naturales siguientes a la recepción del producto, a anular el contrato, a una reducción del precio de compra o a un nuevo pedido dependiendo de las condiciones del mismo y la disponibilidad del producto.</p>
			<p class="text-left medium-text-justify">En el caso de devoluciones a causa de algún defecto de fábrica  printome.mx se hará cargo también de los gastos de envío.</p>
			<p class="text-left medium-text-justify">De acuerdo con el estado actual de la tecnología no puede garantizarse que la comunicación de los datos a través de Internet sea siempre accesible y exenta de errores en todo momento. Por lo tanto printome.mx no es responsable de que la accesibilidad de la oferta online sea permanente e ininterrumpida.</p>
			<p class="text-left medium-text-justify">Para la aplicación de la garantía por defectos de fábrica del cliente es requisito esencial que éste  haya cumplido debidamente con sus obligaciones de comprobación y de reclamación de conformidad con lo estipulado en el presente contrato.</p>
			<p class="text-left medium-text-justify">El plazo de prescripción de los derechos de garantía por defectos de fábrica de la mercancía suministrada es de treinta días naturales contados a partir del momento en el que se recibe la mercancía.</p>
			
			<h3 class="subseccion-titulo">Limitación de Responsabilidad</h3>
			<p class="text-left medium-text-justify">La responsabilidad de printome.com y sus representantes se rige por la normativa legal siempre que en estas Condiciones Generales de Contrato y de Entrega no se determine lo contrario. En ningún caso printome.mx o sus representantes será responsable por daños y perjuicios. En caso de negligencia leve y de violación de una obligación contractual fundamental, la responsabilidad de printome.mx se limitará al resarcimiento del daño previsible que se produce típicamente.</p>
			
			<h3 class="subseccion-titulo">Derechos de Autor de Diseños Impresos, Liberación de Responsabilidad</h3>
			<p class="text-left medium-text-justify">Si el cliente entrega un motivo propio o ejerce cualquier otro tipo de influencia sobre el producto (personalización de texto, imágenes, diseños, etc..), el cliente asegura a printome.mx que dicho texto, imágenes, diseños, etc…  y motivo están exentos de derechos de terceros y derechos de autor en general. El cliente será el único responsable de cualquier violación de los derechos de autor, de los derechos de la protección de la personalidad o los de los derechos sobre el nombre. El cliente también asegura no atentar contra los derechos de terceros al individualizar el producto.</p>
			<p class="text-left medium-text-justify">El cliente libera expresamente a printome.mx  y a sus representantes de todas las exigencias y derechos que se hagan valer por la violación de tales derechos de terceros. El cliente se hará cargo de todos los gastos de la defensa legal y demás daños y perjuicios que se le ocasionen a printome.com y a sus representantes.</p>
			
			<h3 class="subseccion-titulo">Modificaciones Técnicas y de Configuración</h3>
			<p class="text-left medium-text-justify">Nos reservamos explícitamente en el cumplimiento del contrato el derecho a realizar modificaciones con respecto a las descripciones y datos en nuestros prospectos, catálogos y demás documentos escritos y electrónicos en lo que se refiere a características del material, color, peso, dimensiones, configuración o características similares, siempre que éstas sean aceptables para el cliente. Motivos de modificación aceptables pueden resultar de oscilaciones habituales en el comercio y procesos técnicos de producción.</p>
			
			<h3 class="subseccion-titulo">Protección de Datos</h3>
			<p class="text-left medium-text-justify">La página web printome.mx  procesará datos personales del cliente para un fin específico y conforme a las disposiciones legales, printome.mx utilizará para el cumplimiento y la ejecución del contrato los datos personales indicados con el fin de encargar mercancías (como por ejemplo nombre, dirección de e-mail, dirección postal, datos del pago), printome.mx tratará estos datos de forma confidencial y no los entregará a terceros que no participen en el proceso de pedido, entrega y pago. El cliente tendrá derecho a solicitar y recibir gratuitamente información sobre los datos personales que printome.mx haya guardado sobre él. Además tiene derecho a la corrección de datos incorrectos y a que se bloqueen y borren sus datos personales, siempre que no se oponga a esto ninguna obligación legal de conservación de datos.</p>
			
			<h3 class="subseccion-titulo">Lugar de Jurisdicción – Lugar de Ejecución – Determinación del Derecho Aplicable</h3>
			<p class="text-left medium-text-justify">El lugar de ejecución de todos los envíos es la sede comercial de printome.mx ubicada en Yucatán</p>
			<p class="text-left medium-text-justify">Las partes contratantes se someten expresamente a la jurisdicción y competencia de las leyes y tribunales de los Estados Unidos Mexicanos.</p>
			<p class="text-left medium-text-justify">La página web printome.mx también tendrá derecho, a elección propia a demandar al cliente en el lugar de jurisdicción y habitación o sede del comercio de éste. Lo mismo es válido en el caso de que el cliente no disponga de un lugar de jurisdicción general en la Republica Mexicana o si tras el cierre del contrato traslade al extranjero su domicilio o lugar de residencia habitual o su domicilio o lugar de residencia habitual sea desconocido en el momento de la interposición de la demanda.</p>
			<p class="text-left medium-text-justify">El contrato conforme a las disposiciones de estas Condiciones Generales de Contrato y de Entrega está sujeto únicamente a la legislación de los Estados Unidos Mexicanos. Se excluye la validez del derecho de compra y venta de la ONU de aplicación a los negocios transnacionales.</p>
			<p class="text-left medium-text-justify">En el caso de que alguna o varias de las cláusulas de estas Condiciones Generales de Contrato y de Entrega no fuese/n válida/s o se opusiera/n a la normativa legal, esto no afectaría al resto del contrato.</p>

		</div>
	</div>
</div>
<style>
    .terminos-condiciones h1{
        color:#FF4D00 !important;
    }
    .terminos-condiciones h3{
        color:#FF4D00 !important;
    }
    .terminos-condiciones p {
        color: #025573 !important;
    }
</style>